if: type = push and branch = master and repo = 'CodeForPoznan/alinka-website'

language: node_js
node_js: ['12.16']

env:
  global:
    - secure: <waits for input>

install:
  - pip install --user awscli==1.18.0
  - npm install

script:
  - npx gulp sass
  - aws s3 sync . s3://codeforpoznan-public/dev_alinka_website/
    --delete
    --exclude ".git/*"
    --exclude "assets/scss/*"
    --exclude "node_modules/*"
  - aws cloudfront create-invalidation
    --distribution-id E2LRB6U4UM753Y
    --paths "/*"
