services:
  - docker
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
install: npm install
script: npm run test
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  on:
    branch: master
